import os
import sqlite3

class db_helper:
    def __init__(self):

        if 'jobs.db' not in os.listdir():
            self.conn = sqlite3.connect('jobs.db')
            '''
            --- The columns in the Database ---
            id -> An autogenerated integer id.
            job_name -> The name of the script (Omitting the rest of the object is deliberate to not bloat the database with unnecessary information)
            job_parameters -> The parameters the script is to be run with.
            time_added -> The time the job is added to the database.
            exec_time -> The time the script is supposed to run.
            status -> 'Pending', 'Running', 'Done', 'Archive'
            '''
            sql = '''CREATE TABLE jobs(id INTEGER PRIMARY KEY autoincrement, 
                                       job_name TEXT, job_parameters TEXT, 
                                       time_added DATE, exec_time TEXT, status TEXT)'''
            self.conn.execute(sql)
            self.conn.commit()
        else:
            self.conn = sqlite3.connect('jobs.db')

    def add_to_database(conn, script):
        conn.execute('''INSERT INTO active (script_name, script_parameters, time_added, status)''')
    