class db_helper:
    def __init__(self):
        self.conn = create_database()


    def create_database():
        conn = sqlite3.connect('jobs.db')
        return conn


    def set_tables(conn):
        '''
        --- The columns in the Database ---
        id -> An autogenerated integer id.
        job_name -> The name of the script (Omitting the rest of the object is deliberate to not bloat the database with unnecessary information)
        job_parameters -> The parameters the script is to be run with.
        time_added -> The time the job is added to the database.
        exec_time -> The time the script is supposed to run.
        status -> 'Pending', 'Running', 'Done', 'Archive'
        '''
        conn.execute('''CREATE TABLE jobs(
                            id INTEGER PRIMARY KEY autoincrement,
                            job_name TEXT,
                            job_parameters TEXT,
                            time_added DATE,
                            exec_time TEXT,
                            status TEXT
                        )''')
        conn.commit()

    def add_to_database(conn, script):
        conn.execute('''INSERT INTO active (script_name, script_parameters, time_added, status)''')
